services:
    mqtt:
        image: eclipse-mosquitto:2.0
        restart: unless-stopped
        command: 'mosquitto -c /mqttconf/custom.conf'
        volumes:
            - 'mosquitto_data:/mosquitto'
            - './mosquitto/custom.conf:/mqttconf/custom.conf'
            - './mosquitto/mqttcreds.txt:/mqttconf/mqttcreds.txt'
        ports:
            - '1883:1883'

volumes:
  mosquitto_data:
